### ISSUE TITLE
panic in prependArgName

### ISSUE THREAD

**Issue by y0ssar1an** [y0ssar1an/q#13]
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/y0ssar1an/q.prependArgName(0xc420403480, 0x2, 0x2, 0xc42043d0f0, 0x1, 0x1, 0x0, 0x0, 0x2)
	/Users/ryan/go/src/github.com/y0ssar1an/q/helpers.go:156 +0x347
github.com/y0ssar1an/q.Q(0xc4201206c0, 0x1, 0x1)
	/Users/ryan/go/src/github.com/y0ssar1an/q/q.go:182 +0x20a
github.com/apcera/apcera-setup/vendor/github.com/apcera/libretto/virtualmachine/azure/arm.(*VM).deploy(0xc420082340, 0xc4204b4350, 0x5)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/vendor/github.com/apcera/libretto/virtualmachine/azure/arm/util.go:170 +0x30a
github.com/apcera/apcera-setup/vendor/github.com/apcera/libretto/virtualmachine/azure/arm.(*VM).Provision(0xc420082340, 0xc420000180, 0x300000002)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/vendor/github.com/apcera/libretto/virtualmachine/azure/arm/vm.go:135 +0xc1
github.com/apcera/apcera-setup/commands/create.createVM(0xc42047e1e0, 0x1f, 0xc420120ca0)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/commands/create/create.go:368 +0x54
github.com/apcera/apcera-setup/commands/create.createBaseVMs(0xc42028e5a0, 0x3, 0x4, 0x1e49360, 0xc420470630, 0x1e49360, 0xc420470640)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/commands/create/create.go:432 +0x4a3
github.com/apcera/apcera-setup/commands/create.createVMs(0xc42028e5a0, 0x3, 0x4, 0xc4202c0240, 0x0, 0x0, 0x0)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/commands/create/create.go:460 +0xad
github.com/apcera/apcera-setup/commands/create.Run(0xc4202be480, 0x3c6a8f8, 0x0, 0x0, 0xc4202c0240, 0x0, 0x0)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/commands/create/create.go:242 +0x675
github.com/apcera/apcera-setup/commands.ConfiguredCommand.func1(0xc4202be480, 0x3c6a8f8, 0x0, 0x0)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/commands/commands.go:111 +0x1b9
github.com/apcera/apcera-setup/commands.UpdateCheck.func1(0xc4202be480, 0x3c6a8f8, 0x0, 0x0)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/commands/commands.go:169 +0xe5
github.com/apcera/apcera-setup/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202be480, 0x3c6a8f8, 0x0, 0x0, 0xc4202be480, 0x3c6a8f8)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/vendor/github.com/spf13/cobra/command.go:653 +0x2a2
github.com/apcera/apcera-setup/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3c41c20, 0x2210ef1, 0xb, 0xc420121f60)
	/Users/ryan/go/src/github.com/apcera/apcera-setup/vendor/github.com/spf13/cobra/command.go:728 +0x2fe
main.main()
	/Users/ryan/go/src/github.com/apcera/apcera-setup/apcera-setup.go:32 +0x38
```

**Comment by johnSchnake** [comment]
FWIW it looks like the issue is that the list of names given is longer than the list of values. Thats the only thing that makes sense on that line.

**Comment by y0ssar1an** [comment]
I haven't had a single reoccurrence of this panic and I can't reproduce it. I'll reopen if it shows up again.
